# Copyright (c) 2026 VEOR Browser Authors. All rights reserved. 
# Use of this source code is governed by a BSD-style license that can be 
# found in the LICENSE file. 
 
config("veor_infrastructure_public") { 
  include_dirs = [ "//veor/src" ] 
  defines = [ "VEOR_BROWSER" ] 
} 
 
source_set("infrastructure") { 
  sources = [ 
    "storage/IStorageEngine.h", 
    "storage/StorageEngineImpl.h", 
    "storage/StorageEngineImpl.cc", 
    "crypto/ICryptoVault.h", 
    "crypto/CryptoVaultImpl.h", 
    "crypto/CryptoVaultImpl.cc", 
  ] 
  deps = [ 
    "//base", 
    "//sql", 
    "//third_party/sqlite", 
    "//veor/src/core:core", 
  ] 
  public_configs = [ ":veor_infrastructure_public" ] 
  include_dirs = [
    "//third_party/sqlite",
  ]
} 
 
group("storage") { 
  deps = [ ":infrastructure" ] 
} 
 
group("crypto") { 
  deps = [ ":infrastructure" ] 
} 

