# Copyright (c) 2026 VEOR Browser Authors. All rights reserved.

source_set("downloads") {
  sources = [
    "IDownloadController.h",
    "DownloadController.h",
    "DownloadController.cc",
  ]

  deps = [
    "//veor/src/core:core",
  ]

  public_configs = [ "//veor/src/core:veor_core_public" ]
}
