# Copyright (c) 2026 VEOR Browser Authors. All rights reserved.

source_set("compositor") {
  sources = [
    "VeorCompositor.h",
    "VeorCompositor.cc",
  ]

  deps = [
    "//base",
    "//cc",
    "//skia",
    "//ui/compositor",
    "//ui/gfx",
    "//veor/src/core:core",
  ]

  public_configs = [ "//veor/src/core:veor_core_public" ]
}
