# Copyright (c) 2026 VEOR Browser Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/compiler/compiler.gni")

config("veor_core_public") {
  include_dirs = [
    "//veor/src",
    "//base/allocator/partition_allocator/src",
  ]
  defines = [ "VEOR_BROWSER" ]
}

source_set("core") {
  sources = [
    "base/VeorId.h",
    "base/VeorId.cc",
    "base/VeorResult.h",
    "base/VeorResult.cc",
    "logging/VeorLogger.h",
    "logging/VeorLogger.cc",
  ]
  deps = [ "//base" ]
  public_configs = [ ":veor_core_public" ]
}

source_set("test_support") {
  testonly = true
  sources = [
    "test/VeorTest.h",
    "test/VeorTest.cc",
  ]
  deps = [
    "//base",
    "//testing/gtest",
  ]
}

executable("core_unittests") {
  testonly = true
  sources = [
    "base/VeorId_unittest.cc",
    "base/VeorResult_unittest.cc",
  ]
  deps = [
    ":core",
    ":test_support",
    "//testing/gtest",
  ]
}
